---
title: Democat - formerly Digidem Guide
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: tool
email: admin@digidemlab.org
description: Practical tools to create communities and make decisions together.
twitter:
  username: digidemlab
facebook:
  publisher: petter.joelson
logo: "/public/logo.png"
social:
  links:
  - https://www.facebook.com/digidemlab
  - https://github.com/digidemlab/digidem-guide
baseurl: ''
markdown: kramdown
permalink: "/:title/"
gems:
exclude:
- ".sass-cache"
- bower_components
- Rakefile
