---
title: Digidem Guide
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@p-jo.se
description: Practical tools to create communities and make decisions together.
url: http://digidemguide.org
twitter:
  username: digidemlab
facebook:
  publisher: petter.joelson
logo: "/public/logo.png"
social:
  links:
  - https://www.facebook.com/groups/digidemlab
  - https://github.com/digidemlab/digidem-guide
baseurl: ''
markdown: kramdown
permalink: pretty
gems:
- jekyll-seo-tag
exclude:
- ".sass-cache"
- bower_components
- Rakefile
